name: Push to Redocly Reunite (GH Workflow Example)

on:
  push:
    branches:
      - '**'

jobs:
  reunite-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Redocly Reunite push
        uses: redocly/reunite-push-action@v1
        with:
          organization: 'testing_redocly'
          project: 'bartek-lukasz-phronesis'
          mountPath: 'products/api-hub/learning'
          files: 'learning.yaml get-started.md'
        env:
          REDOCLY_AUTHORIZATION: ${{ secrets.REDOCLY_API_KEY }}
